# Generated by Django 4.2.3 on 2023-08-03 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="liked_by_users",
            field=models.ManyToManyField(
                related_name="liked_questions",
                through="topic.Question_Reaction_Table",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
