# Generated by Django 4.2.3 on 2023-08-01 19:29

from django.db import migrations, models
import user.manager
import user.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[user.models.validate_username_no_number],
                    ),
                ),
                (
                    "age",
                    models.DateField(
                        default="2000-06-04",
                        validators=[user.models.validate_age_not_negative],
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (-1, "Female"), (0, "Other")], default="1"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[user.models.email_validator],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", user.manager.UserManager()),
            ],
        ),
    ]
