# Generated by Django 4.2.3 on 2023-08-01 19:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="admin@gmail.com",
                max_length=254,
                unique=True,
                validators=[user.models.email_validator],
            ),
        ),
    ]
