# Generated by Django 4.2.3 on 2023-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_user_id_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
