# Generated by Django 4.2.3 on 2023-08-09 17:40

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_options_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default="",
                max_length=255,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "jpg", "png"]
                    )
                ],
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateField(
                default="", validators=[user.models.validate_age_not_negative]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, validators=[user.models.email_validator]
            ),
        ),
    ]
