# Generated by Django 4.2.3 on 2023-08-16 15:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_profile_picture_alter_user_age_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateField(validators=[user.models.validate_age_not_negative]),
        ),
    ]
