# Generated by Django 4.2.3 on 2023-08-16 15:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateField(
                default="2001/04/22", validators=[user.models.validate_age_not_negative]
            ),
        ),
    ]
